package app.melotrail.application

import app.melotrail.arrangement.core.MidiCoreArrangementStyleCatalog
import app.melotrail.arrangement.core.MidiCorePatternCatalog
import app.melotrail.arrangement.core.MidiCorePerformanceProfileCatalog
import app.melotrail.midi.adapter.JdkMidiReader
import app.melotrail.music.core.ProjectKeySpelling
import app.melotrail.music.core.ProjectMeter
import app.melotrail.music.core.ProjectScaleMode
import app.melotrail.music.core.ProjectTempo
import app.melotrail.project.AuthoritativeChordEvent
import app.melotrail.project.MidiCoreAuthorityHasher
import app.melotrail.project.ProjectKey
import app.melotrail.project.ProjectSectionDefinition
import app.melotrail.project.adapter.MidiCoreArtifactStore
import app.melotrail.structure.MidiCoreBarOccurrencePlacement
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.security.MessageDigest
import java.time.Clock
import java.time.Instant
import java.time.ZoneOffset
import java.util.Base64
import java.util.zip.ZipInputStream
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.longOrNull

/**
 * Development-only MIDI comparison harness for M01. It deliberately drives the
 * current import -> authority -> draft -> acceptance -> export path, so later
 * engine work can compare semantic MIDI packages without audio rendering.
 */
internal class MidiCoreComparisonHarness(private val workRoot: Path) {
    /**
     * Generates only the candidate side. The M01 baseline is a checked-in,
     * immutable snapshot and must never be regenerated by this harness.
     */
    fun captureCandidate(case: M01ComparisonCase, outputRoot: Path): M01ComparisonCapture =
        capture(case, "candidate", outputRoot)

    /** Copies and verifies the immutable M01 package snapshot for one fixture. */
    fun loadBaseline(case: M01ComparisonCase, outputRoot: Path): M01ComparisonCapture =
        M01BaselinePackageResource.load(case, outputRoot, currentAuthoritySha256(case))

    /**
     * The checked-in M01 package records the authority contract that existed
     * when it was frozen. M03 adds the explicit arrangement end to that
     * contract. Rebuild only the current authority digest from the same
     * immutable fixture inputs so the comparison can continue to evaluate the
     * MIDI package, without changing or re-publishing the M01 snapshot.
     */
    private fun currentAuthoritySha256(case: M01ComparisonCase): String {
        val caseWorkRoot = workRoot.resolve("authority").resolve(case.id)
        Files.createDirectories(caseWorkRoot)
        val caseRoot = Files.createTempDirectory(caseWorkRoot, "projection-")
        val input = caseRoot.resolve("input").resolve("${case.id}.mid")
        Files.createDirectories(input.parent)
        Files.write(input, case.sourceBytes)
        val store = MidiCoreArtifactStore()
        val projectRoot = caseRoot.resolve("project")
        val created = MidiCoreProjectLifecycle(store, clock = FIXED_CLOCK, idFactory = { "comparison-${case.id}" })
            .create(CreateMidiCoreProject(projectRoot, "M01 ${case.id}", "comparison-${case.id}", "m01"))
        val session = (created as? MidiCoreProjectLifecycleResult.Opened)?.session
            ?: error("M01 comparison authority projection could not create '${case.id}'.")
        var current = (MidiCoreSourceImport(store).import(ImportMidiCoreSource(session, input)) as? MidiCoreSourceImportResult.Imported)?.session
            ?: error("M01 comparison authority projection could not import '${case.id}'.")
        current = (MidiCoreMusicalAuthority(store).confirm(
            ConfirmMidiCoreAuthority(current, case.key, case.tempo, case.meter),
        ) as? MidiCoreAuthorityResult.Confirmed)?.session
            ?: error("M01 comparison authority projection could not confirm '${case.id}'.")
        current = (MidiCoreStructureTimeline(store).replace(
            ReplaceMidiCoreStructure(
                current,
                case.occurrences.map { ProjectSectionDefinition(it.sectionId, it.label) }.distinctBy(ProjectSectionDefinition::id),
                case.occurrences.map { MidiCoreBarOccurrencePlacement(it.id, it.sectionId, it.label, it.bars) },
            ),
        ) as? MidiCoreStructureTimelineResult.Updated)?.session
            ?: error("M01 comparison authority projection could not structure '${case.id}'.")
        val chords = case.chords.map { chord ->
            AuthoritativeChordEvent(chord.id, chord.occurrenceId, chord.symbol, chord.startTick, chord.endTick)
        }
        current = (MidiCoreAuthoritativeHarmony(store).replace(ReplaceMidiCoreHarmony(current, chords))
            as? MidiCoreAuthoritativeHarmonyResult.Updated)?.session
            ?: error("M01 comparison authority projection could not harmonize '${case.id}'.")
        return MidiCoreAuthorityHasher.from(current.project).sha256
    }

    private fun capture(case: M01ComparisonCase, label: String, outputRoot: Path): M01ComparisonCapture {
        val caseWorkRoot = workRoot.resolve(label).resolve(case.id)
        Files.createDirectories(caseWorkRoot)
        val caseRoot = Files.createTempDirectory(caseWorkRoot, "capture-")
        val input = caseRoot.resolve("input").resolve("${case.id}.mid")
        Files.createDirectories(input.parent)
        Files.write(input, case.sourceBytes)
        val sourceBefore = Files.readAllBytes(input)
        val store = MidiCoreArtifactStore()
        val projectRoot = caseRoot.resolve("project")
        val created = MidiCoreProjectLifecycle(store, clock = FIXED_CLOCK, idFactory = { "comparison-${case.id}" })
            .create(CreateMidiCoreProject(projectRoot, "M01 ${case.id}", "comparison-${case.id}", "m01"))
        val session = (created as? MidiCoreProjectLifecycleResult.Opened)?.session
            ?: return M01ComparisonCapture.Rejected(case.id, "CREATE", "Project creation was rejected", emptyList())
        val imported = MidiCoreSourceImport(store).import(ImportMidiCoreSource(session, input))
        var current = (imported as? MidiCoreSourceImportResult.Imported)?.session
            ?: return M01ComparisonCapture.Rejected(case.id, "SOURCE_IMPORT", imported.toString(), emptyList())
        current = (MidiCoreMusicalAuthority(store).confirm(
            ConfirmMidiCoreAuthority(current, case.key, case.tempo, case.meter),
        ) as? MidiCoreAuthorityResult.Confirmed)?.session
            ?: return M01ComparisonCapture.Rejected(case.id, "AUTHORITY", "Authority confirmation was rejected", emptyList())
        val structured = MidiCoreStructureTimeline(store).replace(
            ReplaceMidiCoreStructure(
                current,
                case.occurrences.map { ProjectSectionDefinition(it.sectionId, it.label) }.distinctBy(ProjectSectionDefinition::id),
                case.occurrences.map { MidiCoreBarOccurrencePlacement(it.id, it.sectionId, it.label, it.bars) },
            ),
        )
        current = (structured as? MidiCoreStructureTimelineResult.Updated)?.session
            ?: return M01ComparisonCapture.Rejected(case.id, "STRUCTURE", structured.rejectionSummary(), emptyList())
        val chords = case.chords.map { chord ->
            AuthoritativeChordEvent(
                chord.id,
                chord.occurrenceId,
                chord.symbol,
                chord.startTick,
                chord.endTick,
            )
        }
        val harmonized = MidiCoreAuthoritativeHarmony(store).replace(ReplaceMidiCoreHarmony(current, chords))
        current = (harmonized as? MidiCoreAuthoritativeHarmonyResult.Updated)?.session
            ?: return M01ComparisonCapture.Rejected(case.id, "HARMONY", harmonized.rejectionSummary(), emptyList())

        val draft = runBlocking {
            MidiCoreArrangementDraftGeneration(store, draftIdFactory = { "draft-${case.id}" }).generate(
                GenerateMidiCoreArrangementDraft(current, case.styleId, case.seed, "draft-${case.id}"),
            )
        }
        val completed = draft as? MidiCoreArrangementDraftGenerationResult.Completed
            ?: return M01ComparisonCapture.Rejected(case.id, "DRAFT", draft.toString(), emptyList())
        current = completed.session
        var acceptanceHistoryIndex = 0
        val accepted = MidiCoreArrangementDraftAcceptance(
            artifacts = store,
            clock = FIXED_CLOCK,
            idFactory = { "accept-${case.id}" },
            historyIdFactory = { "accept-scope-${case.id}-${acceptanceHistoryIndex++}" },
        ).use(UseMidiCoreArrangementDraft(current, completed.draft.id))
        current = (accepted as? MidiCoreArrangementDraftAcceptanceResult.Applied)?.session
            ?: return M01ComparisonCapture.Rejected(case.id, "ACCEPT", accepted.toString(), emptyList())
        val exported = MidiCoreMidiPackageExporter(
            artifacts = store,
            snapshotLifecycle = MidiCoreExportSnapshotLifecycle(store, FIXED_CLOCK, idFactory = { "snapshot-${case.id}" }),
            clock = FIXED_CLOCK,
            snapshotIdFactory = { "comparison-${case.id}" },
        ).export(ExportMidiCorePackage(current))
        val packageResult = (exported as? MidiCoreMidiPackageExportResult.Exported)?.packageResult
            ?: return M01ComparisonCapture.Rejected(case.id, "EXPORT", exported.toString(), emptyList())
        val packageDirectory = outputRoot.resolve(label).resolve(case.id)
        Files.createDirectories(packageDirectory)
        (packageResult.files.map { it.filename } + "manifest.json").forEach { filename ->
            Files.copy(packageResult.directory.resolve(filename), packageDirectory.resolve(filename), StandardCopyOption.REPLACE_EXISTING)
        }
        val sourceAfter = Files.readAllBytes(input)
        val preservedSource = store.verify(projectRoot, requireNotNull(current.project.sourceMidi).original)
        val semanticFiles = packageResult.files.associate { file ->
            file.filename to m01SemanticDigest(packageDirectory.resolve(file.filename))
        }
        val sourceSha256 = m01Sha256(sourceBefore)
        val authoritySha256 = MidiCoreAuthorityHasher.from(current.project).sha256
        val engineInputs = M01EngineInputs.current(case)
        val capture = M01ComparisonCapture.Published(
            case = case,
            sourceSha256 = sourceSha256,
            authoritySha256 = authoritySha256,
            frozenInputsSha256 = m01FrozenInputsSha256(sourceSha256, authoritySha256, engineInputs),
            engineInputs = engineInputs,
            packageDirectory = packageDirectory,
            midiSha256 = packageResult.files.associate { it.filename to it.sha256 },
            semanticSha256 = semanticFiles,
            manifestSha256 = packageResult.manifestSha256,
            sourceUnchanged = sourceBefore.contentEquals(sourceAfter) && sourceBefore.contentEquals(Files.readAllBytes(preservedSource)),
        )
        Files.writeString(packageDirectory.resolve("comparison.json"), captureManifest(capture))
        return capture
    }

    fun writeSideBySideReview(cases: List<M01ComparisonCase>, outputRoot: Path): M01ComparisonReview {
        val baseline = cases.map { loadBaseline(it, outputRoot) }
        val candidate = cases.map { captureCandidate(it, outputRoot) }
        val comparisons = baseline.zip(candidate).map { (left, right) -> compare(left, right) }
        val review = outputRoot.resolve("review.md")
        Files.createDirectories(outputRoot)
        Files.writeString(review, reviewForm(baseline, candidate, comparisons))
        return M01ComparisonReview(baseline, candidate, comparisons, review)
    }

    /** Compares re-imported semantic event streams, never audio bytes or rendered sound. */
    fun compare(baseline: M01ComparisonCapture, candidate: M01ComparisonCapture): M01SemanticComparison {
        if (baseline !is M01ComparisonCapture.Published || candidate !is M01ComparisonCapture.Published) {
            return M01SemanticComparison(false, listOf("Both captures must publish a complete MIDI package."))
        }
        val differences = buildList {
            if (baseline.case.id != candidate.case.id) add("Case identity differs.")
            if (baseline.sourceSha256 != candidate.sourceSha256) add("Protected source digest differs.")
            if (!baseline.sourceUnchanged) add("Baseline source preservation evidence is missing.")
            if (!candidate.sourceUnchanged) add("Candidate generation changed the protected source.")
            if (baseline.authoritySha256 != candidate.authoritySha256) add("Authority digest differs.")
            if (baseline.engineInputs != candidate.engineInputs || baseline.frozenInputsSha256 != candidate.frozenInputsSha256) {
                add("Frozen style, seed, or engine inputs differ.")
            }
            if (baseline.semanticSha256 != candidate.semanticSha256) add("Re-imported semantic MIDI differs.")
            if (baseline.midiSha256 != candidate.midiSha256) add("MIDI byte digest differs.")
        }
        return M01SemanticComparison(differences.isEmpty(), differences)
    }

    private fun reviewForm(
        baseline: List<M01ComparisonCapture>,
        candidate: List<M01ComparisonCapture>,
        comparisons: List<M01SemanticComparison>,
    ): String = buildString {
        appendLine("# M01 MIDI comparison review")
        appendLine()
        appendLine("Development fixtures only; they are not unseen acceptance songs. The only supplied subjective result remains the user's 5/10 average (timing good; piano/melody fit and complete-song development inconsistent).")
        appendLine("Use the same preview mapping for each A/B pair: Melody + Chords = GM Acoustic Grand Piano, Bass = GM Electric Bass (finger), Drums = GM standard kit on channel 10. Compare the listed piano+melody loop before the full arrangement at the same role levels.")
        appendLine()
        appendLine("| Case | Required loops | Baseline package | Candidate package | Captured source / authority / engine inputs | Baseline output hashes | Semantic result | Reviewer score & notes |")
        appendLine("| --- | --- | --- | --- | --- | --- | --- |")
        baseline.zip(candidate).zip(comparisons).forEach { (pair, comparison) ->
            val (left, right) = pair
            val published = left as? M01ComparisonCapture.Published
            val candidatePublished = right as? M01ComparisonCapture.Published
            val frozen = published?.let {
                "`${it.sourceSha256}` / `${it.authoritySha256}`<br>Baseline: ${it.engineInputs.reviewSummary()}<br>Candidate: ${candidatePublished?.engineInputs?.reviewSummary() ?: "capture rejected"}"
            } ?: "capture rejected"
            val hashes = published?.midiSha256?.entries?.joinToString("<br>") { (name, hash) -> "$name: `$hash`" } ?: "—"
            val loops = published?.case?.let { "Piano + melody: ${it.pianoMelodyLoop}; full arrangement: ${it.fullArrangementLoop}" } ?: "—"
            appendLine("| ${left.caseId} | $loops | ${published?.packageDirectory ?: left.summary} | ${candidatePublished?.packageDirectory ?: right.summary} | $frozen | $hashes | ${if (comparison.equivalent) "same" else comparison.differences.joinToString(" ")} | ___ / 10; bars: ___; comments: ___ |")
        }
        appendLine()
        appendLine("Engine IDs and catalog versions above come from each captured package. No listening score is implied by this generated form.")
    }

    private fun captureManifest(capture: M01ComparisonCapture.Published): String = buildString {
        appendLine("{")
        appendLine("  \"caseId\": \"${capture.case.id}\",")
        appendLine("  \"scenarios\": [${capture.case.scenarioTags.sorted().joinToString(", ") { "\"$it\"" }}],")
        appendLine("  \"sourceSha256\": \"${capture.sourceSha256}\",")
        appendLine("  \"authoritySha256\": \"${capture.authoritySha256}\",")
        appendLine("  \"frozenInputsSha256\": \"${capture.frozenInputsSha256}\",")
        appendLine("  \"styleId\": \"${capture.engineInputs.styleId}\",")
        appendLine("  \"styleCatalogVersion\": ${capture.engineInputs.styleCatalogVersion},")
        appendLine("  \"patternCatalogVersion\": ${capture.engineInputs.patternCatalogVersion},")
        appendLine("  \"performanceProfileCatalogVersion\": ${capture.engineInputs.performanceProfileCatalogVersion},")
        appendLine("  \"seed\": ${capture.engineInputs.seed},")
        appendLine("  \"engineId\": \"${capture.engineInputs.engineId}\",")
        appendLine("  \"pianoMelodyLoop\": ${capture.case.pianoMelodyLoop.toJson()},")
        appendLine("  \"fullArrangementLoop\": ${capture.case.fullArrangementLoop.toJson()},")
        appendLine("  \"sourceUnchanged\": ${capture.sourceUnchanged},")
        appendLine("  \"midiSha256\": {${capture.midiSha256.toSortedMap().entries.joinToString(", ") { (name, hash) -> "\"$name\": \"$hash\"" }}},")
        appendLine("  \"semanticSha256\": {${capture.semanticSha256.toSortedMap().entries.joinToString(", ") { (name, hash) -> "\"$name\": \"$hash\"" }}},")
        appendLine("  \"exportManifestSha256\": \"${capture.manifestSha256}\"")
        appendLine("}")
    }

    private companion object {
        val FIXED_CLOCK: Clock = Clock.fixed(Instant.parse("2026-09-07T00:00:00Z"), ZoneOffset.UTC)
    }
}

/**
 * Immutable M01 output package captured before the M02+ engine work.  It is
 * deliberately kept under test resources, rather than ignored build output,
 * so later engine changes can only generate the candidate side of an A/B
 * comparison.  The resource is base64-wrapped solely to keep binary MIDI
 * assets reviewable in a text patch; its decoded ZIP is the owned package.
 */
internal object M01BaselinePackageResource {
    private const val RESOURCE = "fixtures/m01-baseline/packages.zip.base64"
    private val FROZEN_ENGINE_INPUTS = M01EngineInputs(
        styleId = "steady-road",
        styleCatalogVersion = 1,
        patternCatalogVersion = 1,
        performanceProfileCatalogVersion = 1,
        seed = 901,
        engineId = "midi-core-style-v1",
    )
    private val MIDI_FILES = setOf("complete-song.mid", "melody.mid", "chords.mid", "bass.mid", "drums.mid", "manifest.json", "comparison.json")
    private val COMPARISON_FIELDS = setOf(
        "caseId", "scenarios", "sourceSha256", "authoritySha256", "frozenInputsSha256", "styleId",
        "styleCatalogVersion", "patternCatalogVersion", "performanceProfileCatalogVersion", "seed", "engineId",
        "pianoMelodyLoop", "fullArrangementLoop", "sourceUnchanged", "midiSha256", "semanticSha256",
        "exportManifestSha256",
    )

    fun load(case: M01ComparisonCase, outputRoot: Path, currentAuthoritySha256: String): M01ComparisonCapture {
        val target = outputRoot.resolve("baseline").resolve(case.id)
        val entries = resourceEntries(case.id)
        require(entries.keys == MIDI_FILES) { "M01 baseline '${case.id}' has an incomplete package." }
        val comparison = entries.getValue("comparison.json").decodeToString()
        val manifest = entries.getValue("manifest.json")
        val frozen = parseAndValidateManifest(case, comparison)
        val midiSha256 = frozen.midiSha256
        val semanticSha256 = frozen.semanticSha256
        midiSha256.forEach { (filename, expected) ->
            require(m01Sha256(entries.getValue(filename)) == expected) { "M01 baseline MIDI digest mismatch for '$filename'." }
        }
        require(m01Sha256(manifest) == frozen.exportManifestSha256) { "M01 baseline export manifest digest mismatch." }
        Files.createDirectories(target)
        entries.forEach { (filename, bytes) ->
            Files.write(target.resolve(filename), bytes)
        }
        midiSha256.forEach { (filename, _) ->
            require(m01SemanticDigest(target.resolve(filename)) == semanticSha256.getValue(filename)) {
                "M01 baseline semantic digest mismatch for '$filename'."
            }
        }
        // Verify the historical M01 manifest above, then compare it with a
        // current-contract authority digest. M03 makes arrangement extent an
        // authority fact; its absence from the immutable M01 manifest must not
        // turn unchanged MIDI output into a false semantic difference.
        return M01ComparisonCapture.Published(
            case = case,
            sourceSha256 = frozen.sourceSha256,
            authoritySha256 = currentAuthoritySha256,
            frozenInputsSha256 = m01FrozenInputsSha256(
                frozen.sourceSha256,
                currentAuthoritySha256,
                frozen.engineInputs,
            ),
            engineInputs = frozen.engineInputs,
            packageDirectory = target,
            midiSha256 = midiSha256,
            semanticSha256 = semanticSha256,
            manifestSha256 = m01Sha256(manifest),
            sourceUnchanged = true,
        )
    }

    fun validateManifest(case: M01ComparisonCase, document: String) {
        parseAndValidateManifest(case, document)
    }

    private fun resourceEntries(caseId: String): Map<String, ByteArray> {
        val stream = requireNotNull(M01BaselinePackageResource::class.java.classLoader.getResourceAsStream(RESOURCE)) {
            "Missing immutable M01 baseline package resource '$RESOURCE'."
        }
        val prefix = "$caseId/"
        return stream.bufferedReader().use { reader ->
            val decoded = Base64.getMimeDecoder().decode(reader.readText())
            ZipInputStream(decoded.inputStream()).use { archive ->
                buildMap {
                    while (true) {
                        val entry = archive.nextEntry ?: break
                        if (!entry.isDirectory && entry.name.startsWith(prefix)) {
                            val filename = entry.name.removePrefix(prefix)
                            require('/' !in filename && filename in MIDI_FILES) { "Unsafe M01 baseline entry '${entry.name}'." }
                            require(put(filename, archive.readBytes()) == null) { "Duplicate M01 baseline entry '${entry.name}'." }
                        }
                    }
                }
            }
        }
    }

    private fun parseAndValidateManifest(case: M01ComparisonCase, document: String): FrozenManifest {
        val json = Json.parseToJsonElement(document) as? JsonObject
            ?: throw IllegalArgumentException("M01 baseline comparison manifest must be a JSON object.")
        require(json.keys == COMPARISON_FIELDS) { "M01 baseline comparison manifest fields are invalid." }
        val frozen = FrozenManifest(
            caseId = json.requiredString("caseId"),
            scenarios = json.requiredStringList("scenarios"),
            sourceSha256 = json.requiredHash("sourceSha256"),
            authoritySha256 = json.requiredHash("authoritySha256"),
            frozenInputsSha256 = json.requiredHash("frozenInputsSha256"),
            engineInputs = M01EngineInputs(
                styleId = json.requiredString("styleId"),
                styleCatalogVersion = json.requiredLong("styleCatalogVersion"),
                patternCatalogVersion = json.requiredLong("patternCatalogVersion"),
                performanceProfileCatalogVersion = json.requiredLong("performanceProfileCatalogVersion"),
                seed = json.requiredLong("seed"),
                engineId = json.requiredString("engineId"),
            ),
            pianoMelodyLoop = json.requiredLoop("pianoMelodyLoop"),
            fullArrangementLoop = json.requiredLoop("fullArrangementLoop"),
            sourceUnchanged = json.requiredBoolean("sourceUnchanged"),
            midiSha256 = json.requiredHashMap("midiSha256"),
            semanticSha256 = json.requiredHashMap("semanticSha256"),
            exportManifestSha256 = json.requiredHash("exportManifestSha256"),
        )
        require(frozen.caseId == case.id) { "M01 baseline case identity is invalid." }
        require(frozen.scenarios == case.scenarioTags.sorted()) { "M01 baseline scenarios differ from fixture '${case.id}'." }
        require(frozen.sourceSha256 == m01Sha256(case.sourceBytes)) { "M01 baseline source differs from fixture '${case.id}'." }
        require(frozen.authoritySha256 == case.baselineAuthoritySha256) { "M01 baseline authority differs from fixture '${case.id}'." }
        require(frozen.engineInputs.styleId == case.styleId) { "M01 baseline style differs from fixture '${case.id}'." }
        require(frozen.engineInputs.styleId == FROZEN_ENGINE_INPUTS.styleId) { "M01 baseline frozen style is invalid." }
        require(frozen.engineInputs.styleCatalogVersion == FROZEN_ENGINE_INPUTS.styleCatalogVersion) { "M01 baseline style catalog version is invalid." }
        require(frozen.engineInputs.patternCatalogVersion == FROZEN_ENGINE_INPUTS.patternCatalogVersion) { "M01 baseline pattern catalog version is invalid." }
        require(frozen.engineInputs.performanceProfileCatalogVersion == FROZEN_ENGINE_INPUTS.performanceProfileCatalogVersion) { "M01 baseline performance-profile catalog version is invalid." }
        require(frozen.engineInputs.seed == case.seed && frozen.engineInputs.seed == FROZEN_ENGINE_INPUTS.seed) { "M01 baseline seed differs from fixture '${case.id}'." }
        require(frozen.engineInputs.engineId == FROZEN_ENGINE_INPUTS.engineId) { "M01 baseline engine ID is invalid." }
        require(frozen.pianoMelodyLoop == case.pianoMelodyLoop) { "M01 baseline piano/melody review loop differs from fixture '${case.id}'." }
        require(frozen.fullArrangementLoop == case.fullArrangementLoop) { "M01 baseline full-arrangement review loop differs from fixture '${case.id}'." }
        require(frozen.sourceUnchanged) { "M01 baseline source preservation evidence is missing." }
        require(
            frozen.frozenInputsSha256 == m01FrozenInputsSha256(
                frozen.sourceSha256,
                frozen.authoritySha256,
                frozen.engineInputs,
            ),
        ) { "M01 baseline frozen input digest is invalid." }
        val expectedMidiFiles = MIDI_FILES - setOf("manifest.json", "comparison.json")
        require(frozen.midiSha256.keys == expectedMidiFiles) { "M01 baseline MIDI hash manifest is incomplete." }
        require(frozen.semanticSha256.keys == expectedMidiFiles) { "M01 baseline semantic hash manifest is incomplete." }
        return frozen
    }

    private fun JsonObject.requiredString(name: String): String {
        val value = this[name] as? JsonPrimitive
        require(value != null && value.isString) { "M01 baseline comparison manifest has an invalid '$name'." }
        return value.content
    }

    private fun JsonObject.requiredLong(name: String): Long {
        val value = this[name] as? JsonPrimitive
        require(value != null && !value.isString && value.longOrNull != null) { "M01 baseline comparison manifest has an invalid '$name'." }
        return requireNotNull(value.longOrNull)
    }

    private fun JsonObject.requiredBoolean(name: String): Boolean {
        val value = this[name] as? JsonPrimitive
        require(value != null && !value.isString && value.booleanOrNull != null) { "M01 baseline comparison manifest has an invalid '$name'." }
        return requireNotNull(value.booleanOrNull)
    }

    private fun JsonObject.requiredHash(name: String): String = requiredString(name).also { value ->
        require(value.matches(Regex("[0-9a-f]{64}"))) { "M01 baseline comparison manifest has an invalid '$name'." }
    }

    private fun JsonObject.requiredStringList(name: String): List<String> {
        val values = this[name] as? JsonArray
        require(values != null) { "M01 baseline comparison manifest has an invalid '$name'." }
        return values.map { value ->
            require(value is JsonPrimitive && value.isString) { "M01 baseline comparison manifest has an invalid '$name'." }
            value.content
        }
    }

    private fun JsonObject.requiredLoop(name: String): M01ReviewLoop {
        val value = this[name] as? JsonObject
        require(value != null && value.keys == setOf("startBar", "endBar")) { "M01 baseline comparison manifest has an invalid '$name'." }
        val start = value.requiredLong("startBar")
        val end = value.requiredLong("endBar")
        val intRange = Int.MIN_VALUE.toLong()..Int.MAX_VALUE.toLong()
        require(start in intRange && end in intRange) { "M01 baseline comparison manifest has an invalid '$name'." }
        return M01ReviewLoop(start.toInt(), end.toInt())
    }

    private fun JsonObject.requiredHashMap(name: String): Map<String, String> {
        val value = this[name] as? JsonObject
        require(value != null) { "M01 baseline comparison manifest has an invalid '$name'." }
        return value.mapValues { (filename, hash) ->
            require(hash is JsonPrimitive && hash.isString && hash.content.matches(Regex("[0-9a-f]{64}"))) {
                "M01 baseline comparison manifest has an invalid '$name.$filename'."
            }
            hash.content
        }
    }

    private data class FrozenManifest(
        val caseId: String,
        val scenarios: List<String>,
        val sourceSha256: String,
        val authoritySha256: String,
        val frozenInputsSha256: String,
        val engineInputs: M01EngineInputs,
        val pianoMelodyLoop: M01ReviewLoop,
        val fullArrangementLoop: M01ReviewLoop,
        val sourceUnchanged: Boolean,
        val midiSha256: Map<String, String>,
        val semanticSha256: Map<String, String>,
        val exportManifestSha256: String,
    )
}

private fun m01SemanticDigest(path: Path): String {
    val inspection = JdkMidiReader().inspect(path)
    val canonical = inspection.sequence.tracks.joinToString("\n") { track ->
        "${track.index}|" + track.events.joinToString(";") { event -> event.toString() }
    }
    return m01Sha256(canonical.encodeToByteArray())
}

private fun m01Sha256(bytes: ByteArray): String =
    MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

internal fun m01FrozenInputsSha256(
    sourceSha256: String,
    authoritySha256: String,
    engineInputs: M01EngineInputs,
): String =
    m01Sha256(
        listOf(
            sourceSha256,
            authoritySha256,
            engineInputs.styleId,
            engineInputs.seed.toString(),
            engineInputs.engineId,
            "pattern-catalog-v${engineInputs.patternCatalogVersion}",
            "performance-profile-catalog-v${engineInputs.performanceProfileCatalogVersion}",
        ).joinToString("\n").encodeToByteArray(),
    )

private fun MidiCoreStructureTimelineResult.rejectionSummary(): String =
    (this as? MidiCoreStructureTimelineResult.Rejected)?.problem?.message ?: "Structure confirmation was rejected"

private fun MidiCoreAuthoritativeHarmonyResult.rejectionSummary(): String =
    (this as? MidiCoreAuthoritativeHarmonyResult.Rejected)?.problem?.message ?: "Harmony confirmation was rejected"

internal sealed interface M01ComparisonCapture {
    val caseId: String
    val summary: String

    data class Published(
        val case: M01ComparisonCase,
        val sourceSha256: String,
        val authoritySha256: String,
        val frozenInputsSha256: String,
        val engineInputs: M01EngineInputs,
        val packageDirectory: Path,
        val midiSha256: Map<String, String>,
        val semanticSha256: Map<String, String>,
        val manifestSha256: String,
        val sourceUnchanged: Boolean,
    ) : M01ComparisonCapture {
        override val caseId: String get() = case.id
        override val summary: String get() = packageDirectory.toString()
    }

    data class Rejected(override val caseId: String, val stage: String, val reason: String, val files: List<Path>) : M01ComparisonCapture {
        override val summary: String get() = "$stage: $reason"
    }
}

internal data class M01SemanticComparison(val equivalent: Boolean, val differences: List<String>)

internal data class M01EngineInputs(
    val styleId: String,
    val styleCatalogVersion: Long,
    val patternCatalogVersion: Long,
    val performanceProfileCatalogVersion: Long,
    val seed: Long,
    val engineId: String,
) {
    fun reviewSummary(): String =
        "$styleId / seed $seed / `$engineId` / style catalog $styleCatalogVersion / pattern catalog $patternCatalogVersion / performance-profile catalog $performanceProfileCatalogVersion"

    companion object {
        fun current(case: M01ComparisonCase): M01EngineInputs = M01EngineInputs(
            styleId = case.styleId,
            styleCatalogVersion = MidiCoreArrangementStyleCatalog.VERSION.toLong(),
            patternCatalogVersion = MidiCorePatternCatalog.VERSION.toLong(),
            performanceProfileCatalogVersion = MidiCorePerformanceProfileCatalog.VERSION.toLong(),
            seed = case.seed,
            engineId = "midi-core-style-v${MidiCoreArrangementStyleCatalog.VERSION}",
        )
    }
}

internal data class M01ComparisonReview(
    val baseline: List<M01ComparisonCapture>,
    val candidate: List<M01ComparisonCapture>,
    val comparisons: List<M01SemanticComparison>,
    val reviewForm: Path,
)

internal data class M01ComparisonCase(
    val id: String,
    val scenarioTags: Set<String>,
    val sourceBytes: ByteArray,
    val baselineAuthoritySha256: String,
    val meter: ProjectMeter,
    val occurrences: List<M01Occurrence>,
    val chords: List<M01Chord>,
    // This is the current complete-draft style whose authored 4/4 drum density
    // fits its role-validation budget. Freeze it rather than special-casing a
    // partial role package in the comparison baseline.
    val styleId: String = "steady-road",
    val seed: Long = 901L,
    val key: ProjectKey = ProjectKey(ProjectKeySpelling.C, ProjectScaleMode.MAJOR),
    val tempo: ProjectTempo = ProjectTempo(500_000),
    val pianoMelodyLoop: M01ReviewLoop,
    val fullArrangementLoop: M01ReviewLoop,
) {
    init {
        require(id.matches(Regex("[a-z0-9-]+"))) { "Comparison case ID is invalid" }
        require(scenarioTags.isNotEmpty()) { "Comparison case must identify its covered scenarios" }
        require(sourceBytes.isNotEmpty()) { "Comparison case source must not be empty" }
        require(baselineAuthoritySha256.matches(Regex("[0-9a-f]{64}"))) { "Comparison baseline authority hash is invalid" }
        require(occurrences.isNotEmpty()) { "Comparison case needs at least one occurrence" }
        require(chords.isNotEmpty()) { "Comparison case needs authoritative chords" }
        require(styleId.isNotBlank()) { "Comparison style is required" }
        val totalBars = occurrences.sumOf(M01Occurrence::bars)
        require(pianoMelodyLoop.endBar <= totalBars && fullArrangementLoop.endBar <= totalBars) {
            "Comparison review loops must remain within the authoritative structure"
        }
    }
}

internal data class M01ReviewLoop(val startBar: Int, val endBar: Int) {
    init { require(startBar > 0 && endBar >= startBar) { "Comparison review loop must cover one or more positive bars" } }

    override fun toString(): String = "bars $startBar–$endBar"

    fun toJson(): String = "{\"startBar\": $startBar, \"endBar\": $endBar}"
}

internal data class M01Occurrence(val id: String, val sectionId: String, val label: String, val bars: Int) {
    init { require(id.isNotBlank() && sectionId.isNotBlank() && label.isNotBlank() && bars > 0) }
}

internal data class M01Chord(
    val id: String,
    val occurrenceId: String,
    val symbol: String,
    val startTick: Long,
    val endTick: Long,
) {
    init { require(id.isNotBlank() && occurrenceId.isNotBlank() && symbol.isNotBlank() && startTick >= 0 && endTick > startTick) }
}

/** Hand-authored raw SMF fixtures keep the harness independent from the production writer. */
internal object M01ComparisonFixtures {
    val cases: List<M01ComparisonCase> = listOf(
        M01ComparisonCase(
            id = "repeated-chorus-bridge",
            scenarioTags = setOf(
                "held-close-melody-piano", "passing-tones", "low-register", "sub-bar-chords",
                "repeated-chorus", "bridge", "expressive-pedal", "initial-silence",
                "dense-sparse-phrases", "ending",
            ),
            sourceBytes = rawMidi(4, 2, listOf(
                note(240, 72, 960), note(960, 74, 1200), note(1200, 76, 1920),
                note(1920, 50, 2880), note(2880, 69, 3840), note(3840, 71, 4800),
                note(4800, 72, 5760), note(5760, 74, 6720), note(7200, 76, 7680),
            ), withExpression = true),
            baselineAuthoritySha256 = "6d18acddd88025f35972999956abd185da73a92d49f1b1347286483ff60e2a61",
            meter = ProjectMeter(4, 2),
            occurrences = listOf(
                M01Occurrence("verse-1", "verse", "Verse", 1),
                M01Occurrence("chorus-1", "chorus", "Chorus", 1),
                M01Occurrence("bridge-1", "bridge", "Bridge", 1),
                M01Occurrence("chorus-2", "chorus", "Chorus", 1),
            ),
            chords = listOf(
                M01Chord("verse-c", "verse-1", "C", 0, 960),
                M01Chord("verse-am", "verse-1", "Am", 960, 1920),
                M01Chord("chorus-g", "chorus-1", "G", 1920, 3840),
                M01Chord("bridge-f", "bridge-1", "F", 3840, 5760),
                M01Chord("chorus-return", "chorus-2", "C", 5760, 7680),
            ),
            pianoMelodyLoop = M01ReviewLoop(1, 2),
            fullArrangementLoop = M01ReviewLoop(1, 4),
        ),
        meterCase("three-four", ProjectMeter(3, 2), "3-4"),
        meterCase("six-eight", ProjectMeter(6, 3), "6-8"),
    )

    fun invalidCase(): M01ComparisonCase = cases.first().copy(id = "invalid-source", sourceBytes = byteArrayOf(0x4d, 0x54, 0x68, 0x64))

    private fun meterCase(id: String, meter: ProjectMeter, tag: String): M01ComparisonCase {
        val barTicks = 480L * meter.numerator * 4 / meter.denominator
        return M01ComparisonCase(
            id = id,
            scenarioTags = setOf(tag, "ending"),
            sourceBytes = rawMidi(meter.numerator, meter.denominatorExponent, listOf(note(0, 67, barTicks))),
            baselineAuthoritySha256 = when (id) {
                "three-four" -> "29a6733f71899a096366d8b86d36bacdccfa10890ff2fea959a2661175d71fb8"
                "six-eight" -> "374ae7fd305e422ed519b3ba79a5c408672b5a7ec72661292160dca95dd12be1"
                else -> error("Missing frozen M01 authority hash for '$id'")
            },
            meter = meter,
            occurrences = listOf(M01Occurrence("$id-1", id, tag, 1)),
            chords = listOf(M01Chord("$id-c", "$id-1", "C", 0, barTicks)),
            pianoMelodyLoop = M01ReviewLoop(1, 1),
            fullArrangementLoop = M01ReviewLoop(1, 1),
        )
    }

    private data class RawNote(val start: Long, val pitch: Int, val end: Long)
    private fun note(start: Long, pitch: Int, end: Long) = RawNote(start, pitch, end)

    private fun rawMidi(numerator: Int, denominatorExponent: Int, notes: List<RawNote>, withExpression: Boolean = false): ByteArray {
        val conductor = track(trackName("Conductor"), tempo(), meter(numerator, denominatorExponent), end())
        val events = mutableListOf<RawEvent>()
        if (withExpression) {
            events += RawEvent(0, bytes(0xb0, 64, 127))
            events += RawEvent(480, bytes(0xe0, 0, 72))
            events += RawEvent(notes.maxOf(RawNote::end), bytes(0xb0, 64, 0))
        }
        notes.forEach { note ->
            events += RawEvent(note.start, bytes(0x90, note.pitch, 92))
            events += RawEvent(note.end, bytes(0x80, note.pitch, 48))
        }
        val melodyEvents = events.sortedWith(compareBy<RawEvent> { it.tick }.thenBy { it.data[0].toInt() and 0xff })
            .fold(Pair(0L, byteArrayOf())) { (last, bytes), event ->
                event.tick to (bytes + vlq((event.tick - last).toInt()) + event.data)
            }.second + end()
        // The fixture ticks are authored at the target workflow's 480 PPQ. The
        // header must use that same division so source extent and bar placement
        // remain authoritative and deterministic.
        return "MThd".encodeToByteArray() + bytes(0, 0, 0, 6, 0, 1, 0, 2, 1, 0xe0) + conductor + chunk("MTrk", trackName("Melody") + melodyEvents)
    }

    private data class RawEvent(val tick: Long, val data: ByteArray)
    private fun trackName(name: String): ByteArray = vlq(0) + bytes(0xff, 0x03, name.length) + name.encodeToByteArray()
    private fun tempo(): ByteArray = vlq(0) + bytes(0xff, 0x51, 3, 0x07, 0xa1, 0x20)
    private fun meter(numerator: Int, denominatorExponent: Int): ByteArray = vlq(0) + bytes(0xff, 0x58, 4, numerator, denominatorExponent, 24, 8)
    private fun end(): ByteArray = vlq(0) + bytes(0xff, 0x2f, 0)
    private fun track(vararg events: ByteArray): ByteArray = chunk("MTrk", events.fold(byteArrayOf()) { all, event -> all + event })
    private fun chunk(name: String, payload: ByteArray): ByteArray = name.encodeToByteArray() + bytes(payload.size ushr 24, payload.size ushr 16, payload.size ushr 8, payload.size) + payload
    private fun bytes(vararg values: Int): ByteArray = values.map(Int::toByte).toByteArray()
    private fun vlq(value: Int): ByteArray {
        require(value >= 0)
        val groups = mutableListOf<Int>()
        var remaining = value
        do { groups += remaining and 0x7f; remaining = remaining ushr 7 } while (remaining > 0)
        return groups.asReversed().mapIndexed { index, group -> (if (index == groups.lastIndex) group else group or 0x80).toByte() }.toByteArray()
    }
}
