server.port=${SERVER_PORT:8080}
server.address=${SERVER_HOST:localhost}
server.worker-base-url=${WORKER_BASE_URL:http://localhost:8081}
server.project-storage-path=${PROJECT_STORAGE_PATH:data/projects}
server.audio-storage-path=${AUDIO_STORAGE_PATH:data/audio}
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
