package app.melotrail.midi

import app.melotrail.application.CreateMidiCoreProject
import app.melotrail.application.ImportMidiCoreSource
import app.melotrail.application.MidiCoreProjectLifecycle
import app.melotrail.application.MidiCoreProjectLifecycleResult
import app.melotrail.application.MidiCoreSourceImport
import app.melotrail.application.MidiCoreSourceImportProblemCode
import app.melotrail.application.MidiCoreSourceImportResult
import app.melotrail.midi.adapter.JdkMidiReader
import app.melotrail.midi.adapter.JdkMidiWriter
import app.melotrail.midi.domain.MidiBeatPosition
import app.melotrail.midi.domain.MidiChannelPressureEvent
import app.melotrail.midi.domain.MidiControlChangeEvent
import app.melotrail.midi.domain.MidiEventOrderingKey
import app.melotrail.midi.domain.MidiExportMarker
import app.melotrail.midi.domain.MidiExportRole
import app.melotrail.midi.domain.MidiExportRoleTrack
import app.melotrail.midi.domain.MidiExportSong
import app.melotrail.midi.domain.MidiMarkerEvent
import app.melotrail.midi.domain.MidiNoteEvent
import app.melotrail.midi.domain.MidiPitchBendEvent
import app.melotrail.midi.domain.MidiPpq
import app.melotrail.midi.domain.MidiReaderIssueCode
import app.melotrail.midi.domain.MidiSemanticEventKind
import app.melotrail.midi.domain.MidiTrackNameEvent
import app.melotrail.midi.domain.MidiUnsupportedEvent
import app.melotrail.midi.domain.SemanticMidiEvent
import app.melotrail.music.core.ProjectKeySpelling
import app.melotrail.music.core.ProjectMeter
import app.melotrail.music.core.ProjectScaleMode
import app.melotrail.music.core.ProjectTempo
import app.melotrail.project.AuthoritativeChordEvent
import app.melotrail.project.CandidateAcceptance
import app.melotrail.project.CandidateRole
import app.melotrail.project.MidiCoreCandidate
import app.melotrail.project.MidiCoreCandidateStatus
import app.melotrail.project.MidiCoreProject
import app.melotrail.project.MidiCoreProjectDocument
import app.melotrail.project.MidiCoreProjectSchema
import app.melotrail.project.ProjectArtifact
import app.melotrail.project.ProjectAuthority
import app.melotrail.project.ProjectId
import app.melotrail.project.ProjectKey
import app.melotrail.project.ProjectMetadata
import app.melotrail.project.ProjectRelativePath
import app.melotrail.project.ProjectSectionDefinition
import app.melotrail.project.SelectedMelodyTrack
import app.melotrail.project.SourceMidiRecord
import app.melotrail.project.adapter.MidiCoreArtifactStore
import app.melotrail.structure.MidiCoreHarmonyFindingCode
import app.melotrail.structure.MidiCoreHarmonyValidator
import app.melotrail.structure.MidiCoreOccurrencePlacement
import app.melotrail.structure.MidiCoreOccurrenceTimeline
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import kotlin.math.abs
import kotlin.random.Random
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Timeout
import org.junit.jupiter.api.io.TempDir

/**
 * Fixed-seed property cases for the target MIDI Core boundary.
 *
 * Case counts and generated byte sizes intentionally stay small: this suite is
 * regression coverage, never an unbounded fuzzer or a source of nondeterminism.
 */
@Timeout(20)
class MidiCoreBoundedPropertyTest {
    @TempDir lateinit var root: Path

    @Test
    fun `seeded malformed SMF chunks always return a typed import rejection`() {
        val random = Random(MALFORMED_MIDI_SEED)
        val store = MidiCoreArtifactStore()
        val lifecycle = MidiCoreProjectLifecycle(artifacts = store)

        repeat(MALFORMED_MIDI_CASES) { caseIndex ->
            val projectRoot = root.resolve("malformed-$caseIndex")
            val session = assertIs<MidiCoreProjectLifecycleResult.Opened>(
                lifecycle.create(CreateMidiCoreProject(projectRoot, "Malformed $caseIndex", "malformed-$caseIndex")),
            ).session
            val source = root.resolve("malformed-$caseIndex.mid")
            val bytes = malformedSmf(random, caseIndex)
            assertTrue(bytes.size <= MAX_MALFORMED_MIDI_BYTES, "seed=$MALFORMED_MIDI_SEED case=$caseIndex exceeded the byte bound")
            Files.write(source, bytes)

            val result = MidiCoreSourceImport(store).import(ImportMidiCoreSource(session, source))
            val rejected = assertIs<MidiCoreSourceImportResult.Rejected>(result, "seed=$MALFORMED_MIDI_SEED case=$caseIndex result=$result")
            assertEquals(MidiCoreSourceImportProblemCode.INVALID_MIDI, rejected.problem.code, "seed=$MALFORMED_MIDI_SEED case=$caseIndex")
            assertEquals(null, store.openProject(projectRoot).sourceMidi, "seed=$MALFORMED_MIDI_SEED case=$caseIndex must not publish source artifacts")
        }
    }

    @Test
    fun `seeded unpaired note events remain bounded findings and never publish a source`() {
        val random = Random(NOTE_PAIRING_SEED)
        val store = MidiCoreArtifactStore()
        val lifecycle = MidiCoreProjectLifecycle(artifacts = store)
        val reader = JdkMidiReader()

        repeat(NOTE_PAIRING_CASES) { caseIndex ->
            val projectRoot = root.resolve("unpaired-$caseIndex")
            val session = assertIs<MidiCoreProjectLifecycleResult.Opened>(
                lifecycle.create(CreateMidiCoreProject(projectRoot, "Unpaired $caseIndex", "unpaired-$caseIndex")),
            ).session
            val expectedIssue = if (caseIndex % 2 == 0) MidiReaderIssueCode.UNCLOSED_NOTE_ON else MidiReaderIssueCode.ORPHAN_NOTE_OFF
            val source = root.resolve("unpaired-$caseIndex.mid")
            Files.write(source, unpairedNoteSmf(random, expectedIssue))

            val inspection = reader.inspect(source)
            assertTrue(inspection.findings.any { it.code == expectedIssue }, "seed=$NOTE_PAIRING_SEED case=$caseIndex expected=$expectedIssue")
            val result = MidiCoreSourceImport(store).import(ImportMidiCoreSource(session, source))
            val rejected = assertIs<MidiCoreSourceImportResult.Rejected>(result, "seed=$NOTE_PAIRING_SEED case=$caseIndex result=$result")
            assertEquals(MidiCoreSourceImportProblemCode.IMPORT_REJECTED, rejected.problem.code, "seed=$NOTE_PAIRING_SEED case=$caseIndex")
            assertEquals(null, store.openProject(projectRoot).sourceMidi, "seed=$NOTE_PAIRING_SEED case=$caseIndex must not publish malformed pairing")
        }
    }

    @Test
    fun `seeded rational timing cases keep documented rounding bounds`() {
        val random = Random(RATIONAL_TIMING_SEED)

        repeat(RATIONAL_TIMING_CASES) { caseIndex ->
            val ppq = MidiPpq(random.nextInt(1, 2_048))
            val numerator = random.nextInt(0, 20_000).toLong()
            val denominator = random.nextInt(1, 1_024).toLong()
            val position = MidiBeatPosition.of(numerator, denominator)
            val ticks = position.toTicks(ppq)
            val exactNumerator = position.numerator * ppq.value.toLong()
            val roundingErrorTwice = abs(ticks * position.denominator - exactNumerator) * 2L

            assertTrue(ticks >= 0L, "seed=$RATIONAL_TIMING_SEED case=$caseIndex")
            assertTrue(roundingErrorTwice <= position.denominator, "seed=$RATIONAL_TIMING_SEED case=$caseIndex exceeds nearest-ties-up bound")
            assertEquals(ticks, position.toTicks(ppq), "seed=$RATIONAL_TIMING_SEED case=$caseIndex is not deterministic")
            if (exactNumerator % position.denominator == 0L) {
                assertEquals(position, MidiBeatPosition.fromTicks(ticks, ppq), "seed=$RATIONAL_TIMING_SEED case=$caseIndex should round-trip exactly")
            }
        }
    }

    @Test
    fun `seeded authority timelines stay contiguous and malformed chord coverage is typed`() {
        val random = Random(AUTHORITY_TIMELINE_SEED)
        val ppq = MidiPpq(480)
        val meter = ProjectMeter(4, 2)

        repeat(AUTHORITY_TIMELINE_CASES) { caseIndex ->
            val count = random.nextInt(1, 5)
            val definitions = (0 until count).map { index -> ProjectSectionDefinition("section-$caseIndex-$index", "Section $index") }
            val placements = definitions.mapIndexed { index, definition ->
                MidiCoreOccurrencePlacement(
                    id = "occurrence-$caseIndex-$index",
                    definitionId = definition.id,
                    label = "Occurrence $index",
                    durationTicks = random.nextInt(2, 1_921).toLong(),
                )
            }
            val timeline = MidiCoreOccurrenceTimeline.build(ppq, meter, definitions, placements)
            assertEquals(0L, timeline.occurrences.first().startTick, "seed=$AUTHORITY_TIMELINE_SEED case=$caseIndex")
            assertTrue(timeline.occurrences.zipWithNext().all { (left, right) -> left.endTick == right.startTick }, "seed=$AUTHORITY_TIMELINE_SEED case=$caseIndex")

            val chords = timeline.occurrences.mapIndexed { index, occurrence ->
                AuthoritativeChordEvent("chord-$caseIndex-$index", occurrence.id, if (index % 2 == 0) "C" else "Am", occurrence.startTick, occurrence.endTick)
            }
            val authority = ProjectAuthority(
                ProjectKey(ProjectKeySpelling.C, ProjectScaleMode.MAJOR),
                ProjectTempo(500_000),
                meter,
                definitions,
                timeline.occurrences,
                chords,
            )
            assertTrue(MidiCoreHarmonyValidator.validate(authority).valid, "seed=$AUTHORITY_TIMELINE_SEED case=$caseIndex valid coverage rejected")

            val malformed = authority.copy(chordEvents = chords.mapIndexed { index, chord ->
                if (index == 0) chord.copy(startTick = chord.startTick + 1L) else chord
            })
            val validation = MidiCoreHarmonyValidator.validate(malformed)
            assertFalse(validation.valid, "seed=$AUTHORITY_TIMELINE_SEED case=$caseIndex malformed coverage passed")
            assertTrue(validation.findings.any { it.code == MidiCoreHarmonyFindingCode.CHORD_WINDOW_GAP }, "seed=$AUTHORITY_TIMELINE_SEED case=$caseIndex missing typed gap finding")
        }
    }

    @Test
    fun `seeded project JSON and path mutations retain only valid candidate states`() {
        val random = Random(PROJECT_JSON_SEED)

        repeat(PROJECT_JSON_CASES) { caseIndex ->
            val project = propertyProject(caseIndex, random.nextLong())
            val serialized = MidiCoreProjectSchema.encode(project)
            assertTrue(serialized.length <= MAX_PROJECT_JSON_CHARS, "seed=$PROJECT_JSON_SEED case=$caseIndex exceeded JSON bound")
            assertEquals(project, MidiCoreProjectSchema.decode(serialized), "seed=$PROJECT_JSON_SEED case=$caseIndex did not round-trip")
            assertEquals(serialized, MidiCoreProjectSchema.encode(MidiCoreProjectSchema.decode(serialized)), "seed=$PROJECT_JSON_SEED case=$caseIndex is not deterministic")

            val unsafePath = listOf("../outside-$caseIndex.mid", "/absolute-$caseIndex.mid", "C:/outside-$caseIndex.mid", "source/../outside-$caseIndex.mid")[caseIndex % 4]
            val mutated = serialized.replace("source/original-$caseIndex.mid", unsafePath)
            assertIs<MidiCoreProjectDocument.Invalid>(MidiCoreProjectSchema.inspect(mutated), "seed=$PROJECT_JSON_SEED case=$caseIndex unsafe path was accepted")

            val accepted = project.candidates.single()
            assertFailsWith<IllegalArgumentException>("seed=$PROJECT_JSON_SEED case=$caseIndex rejected candidate retained an acceptance") {
                project.copy(candidates = listOf(accepted.copy(status = MidiCoreCandidateStatus.REJECTED, rejectionReason = "Property rejection")))
            }
        }
    }

    @Test
    fun `seeded semantic songs writer reader round trip without program changes`() {
        val random = Random(WRITER_READER_SEED)
        val writer = JdkMidiWriter()
        val reader = JdkMidiReader()

        repeat(WRITER_READER_CASES) { caseIndex ->
            val song = propertySong(caseIndex, random)
            val output = root.resolve("round-trip-$caseIndex.mid")
            writer.writeComplete(song, output)
            val inspected = reader.inspect(output)

            assertEquals(1, inspected.sequence.source.format, "seed=$WRITER_READER_SEED case=$caseIndex")
            assertEquals(song.ppq, inspected.sequence.source.ppq, "seed=$WRITER_READER_SEED case=$caseIndex")
            assertEquals(song.songEndTick, inspected.sourceEndTick, "seed=$WRITER_READER_SEED case=$caseIndex")
            assertEquals(listOf("Conductor") + song.roles.map { it.role.trackName }, inspected.trackSummaries.map { it.name }, "seed=$WRITER_READER_SEED case=$caseIndex")
            assertEquals(song.markers.map(MidiExportMarker::renderedLabel), inspected.sequence.tracks.first().events.filterIsInstance<MidiMarkerEvent>().map(MidiMarkerEvent::marker), "seed=$WRITER_READER_SEED case=$caseIndex")
            assertTrue(inspected.sequence.tracks.drop(1).flatMap { it.events }.none { it is MidiUnsupportedEvent }, "seed=$WRITER_READER_SEED case=$caseIndex emitted an unsupported/program event")

            song.roles.forEachIndexed { index, expectedTrack ->
                val actual = inspected.sequence.tracks[index + 1].events.filterNot { it is MidiTrackNameEvent }
                assertEquals(
                    expectedTrack.events.map { semanticFact(it, expectedTrack.role.channel) },
                    actual.map { semanticFact(it) },
                    "seed=$WRITER_READER_SEED case=$caseIndex role=${expectedTrack.role}",
                )
            }
        }
    }

    private fun malformedSmf(random: Random, caseIndex: Int): ByteArray = when (caseIndex % 3) {
        0 -> ByteArray(random.nextInt(1, 33)) { random.nextInt(0, 256).toByte() }.also { it[0] = 0 }
        1 -> "MThd".toByteArray(StandardCharsets.US_ASCII) + ByteArray(random.nextInt(0, 10)) { random.nextInt(0, 256).toByte() }
        else -> smfHeader() + "MTrk".toByteArray(StandardCharsets.US_ASCII) + intBytes(64 + random.nextInt(64)) + ByteArray(random.nextInt(0, 32)) { random.nextInt(0, 256).toByte() }
    }

    private fun smfHeader(): ByteArray = "MThd".toByteArray(StandardCharsets.US_ASCII) + intBytes(6) + byteArrayOf(0, 1, 0, 1, 1, -32)

    private fun unpairedNoteSmf(random: Random, issue: MidiReaderIssueCode): ByteArray {
        val pitch = random.nextInt(0, 128).toByte()
        val velocity = random.nextInt(1, 128).toByte()
        val delta = random.nextInt(0, 120).toByte()
        val noteEvent = when (issue) {
            MidiReaderIssueCode.UNCLOSED_NOTE_ON -> byteArrayOf(0, -112, pitch, velocity)
            MidiReaderIssueCode.ORPHAN_NOTE_OFF -> byteArrayOf(0, -128, pitch, velocity)
            else -> error("Only note-pairing issues are generated here")
        }
        val track = byteArrayOf(
            0, -1, 0x51, 3, 0x07, -95, 0x20,
            0, -1, 0x58, 4, 4, 2, 24, 8,
        ) + noteEvent + byteArrayOf(delta, -1, 0x2f, 0)
        return "MThd".toByteArray(StandardCharsets.US_ASCII) + intBytes(6) + byteArrayOf(0, 0, 0, 1, 1, -32) +
            "MTrk".toByteArray(StandardCharsets.US_ASCII) + intBytes(track.size) + track
    }

    private fun intBytes(value: Int): ByteArray = byteArrayOf(
        (value ushr 24).toByte(),
        (value ushr 16).toByte(),
        (value ushr 8).toByte(),
        value.toByte(),
    )

    private fun propertyProject(caseIndex: Int, seed: Long): MidiCoreProject {
        val sourceHash = hash('a', caseIndex)
        val authorityHash = hash('b', caseIndex)
        val candidateHash = hash('c', caseIndex)
        val reportHash = hash('d', caseIndex)
        val definition = ProjectSectionDefinition("section-$caseIndex", "Section $caseIndex")
        val occurrence = app.melotrail.project.ProjectSectionOccurrence("occurrence-$caseIndex", definition.id, "Occurrence $caseIndex", 0, 480)
        val candidate = MidiCoreCandidate(
            id = "candidate-$caseIndex",
            role = CandidateRole.entries[caseIndex % CandidateRole.entries.size],
            occurrenceId = occurrence.id,
            generatorVersion = "property-v1",
            authorityHash = authorityHash,
            seed = seed,
            midi = artifact("candidates/candidate-$caseIndex.mid", candidateHash),
            validationReport = artifact("reports/candidate-$caseIndex.json", reportHash),
            createdAt = "2026-08-28T00:00:00Z",
            profileId = "property",
            patternId = "property.pattern",
            status = MidiCoreCandidateStatus.ACCEPTED,
        )
        return MidiCoreProject(
            id = ProjectId("property-$caseIndex"),
            metadata = ProjectMetadata("Property $caseIndex", "2026-08-28T00:00:00Z", "property-v1"),
            sourceMidi = SourceMidiRecord(
                "source-$caseIndex.mid",
                sourceHash,
                1,
                480,
                artifact("source/original-$caseIndex.mid", sourceHash),
                artifact("reports/import-$caseIndex.json", hash('e', caseIndex)),
                emptyList(),
                480,
            ),
            selectedMelody = SelectedMelodyTrack(0, 0, hash('f', caseIndex)),
            authority = ProjectAuthority(
                ProjectKey(ProjectKeySpelling.C, ProjectScaleMode.MAJOR),
                ProjectTempo(500_000),
                ProjectMeter(4, 2),
                listOf(definition),
                listOf(occurrence),
                listOf(AuthoritativeChordEvent("chord-$caseIndex", occurrence.id, "C", 0, 480)),
            ),
            candidates = listOf(candidate),
            acceptances = listOf(CandidateAcceptance(occurrence.id, candidate.role, candidate.id, locked = false)),
            revision = caseIndex.toLong(),
        )
    }

    private fun propertySong(caseIndex: Int, random: Random): MidiExportSong {
        val ppq = MidiPpq(listOf(96, 240, 480, 960)[caseIndex % 4])
        val songEnd = ppq.value.toLong() * (4L + random.nextInt(4).toLong())
        val roles = MidiExportRole.entries.map { role ->
            MidiExportRoleTrack(role, propertyRoleEvents(role, songEnd, random))
        }
        return MidiExportSong(
            ppq = ppq,
            sequenceName = "Property $caseIndex",
            tempoMicrosecondsPerQuarter = random.nextInt(300_000, 800_000),
            meterNumerator = 4,
            meterDenominatorExponent = 2,
            markers = listOf(MidiExportMarker(1, "Intro $caseIndex", 0), MidiExportMarker(2, "Verse $caseIndex", songEnd / 2L)),
            roles = roles,
            songEndTick = songEnd,
        )
    }

    private fun propertyRoleEvents(role: MidiExportRole, songEnd: Long, random: Random): List<SemanticMidiEvent> {
        val noteCount = random.nextInt(1, 5)
        val slot = songEnd / (noteCount + 1L)
        val notes = (0 until noteCount).map { index ->
            val start = slot * index + random.nextLong(0L, maxOf(1L, slot / 4L))
            val duration = random.nextLong(1L, maxOf(2L, slot / 2L))
            MidiNoteEvent(
                generatedKey(start, MidiSemanticEventKind.NOTE, 100L + index),
                minOf(songEnd, start + duration),
                random.nextInt(0, 16),
                random.nextInt(36, 97),
                random.nextInt(40, 121),
                random.nextInt(0, 128),
            )
        }
        val expression = if (role == MidiExportRole.MELODY) {
            listOf(
                MidiControlChangeEvent(generatedKey(0, MidiSemanticEventKind.CONTROL_CHANGE, 1), random.nextInt(0, 16), 64, random.nextInt(0, 128)),
                MidiPitchBendEvent(generatedKey(songEnd / 2L, MidiSemanticEventKind.PITCH_BEND, 2), random.nextInt(0, 16), random.nextInt(-8_192, 8_192)),
                MidiChannelPressureEvent(generatedKey(songEnd / 2L, MidiSemanticEventKind.CHANNEL_PRESSURE, 3), random.nextInt(0, 16), random.nextInt(0, 128)),
            )
        } else {
            emptyList()
        }
        return (expression + notes).sortedBy(SemanticMidiEvent::orderingKey)
    }

    private fun semanticFact(event: SemanticMidiEvent, channelOverride: Int? = null): String = when (event) {
        is MidiNoteEvent -> "note:${event.orderingKey.tick}:${event.endTick}:${channelOverride ?: event.channel}:${event.pitch}:${event.velocity}:${event.releaseVelocity}"
        is MidiControlChangeEvent -> "cc:${event.orderingKey.tick}:${channelOverride ?: event.channel}:${event.controller}:${event.value}"
        is MidiPitchBendEvent -> "bend:${event.orderingKey.tick}:${channelOverride ?: event.channel}:${event.value}"
        is MidiChannelPressureEvent -> "pressure:${event.orderingKey.tick}:${channelOverride ?: event.channel}:${event.pressure}"
        else -> error("Unexpected property round-trip event: $event")
    }

    private fun generatedKey(tick: Long, kind: MidiSemanticEventKind, id: Long): MidiEventOrderingKey =
        MidiEventOrderingKey(tick, kind, generatedEventKey = id)

    private fun artifact(path: String, sha256: String): ProjectArtifact = ProjectArtifact(ProjectRelativePath(path), sha256)

    private fun hash(prefix: Char, caseIndex: Int): String = prefix.toString().repeat(60) + caseIndex.toString().padStart(4, '0')

    private companion object {
        const val MALFORMED_MIDI_SEED = 47_001
        const val RATIONAL_TIMING_SEED = 47_002
        const val AUTHORITY_TIMELINE_SEED = 47_003
        const val PROJECT_JSON_SEED = 47_004
        const val WRITER_READER_SEED = 47_005
        const val NOTE_PAIRING_SEED = 47_006
        const val MALFORMED_MIDI_CASES = 64
        const val NOTE_PAIRING_CASES = 48
        const val RATIONAL_TIMING_CASES = 128
        const val AUTHORITY_TIMELINE_CASES = 64
        const val PROJECT_JSON_CASES = 48
        const val WRITER_READER_CASES = 48
        const val MAX_MALFORMED_MIDI_BYTES = 128
        const val MAX_PROJECT_JSON_CHARS = 8_192
    }
}
